# Generated by Django 5.2.1 on 2025-05-27 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+254712345678' or '0712345678'. Up to 15 digits allowed.", regex='^\\+?\\d{10,15}$')]),
        ),
    ]
