# Generated by Django 5.2.1 on 2025-05-27 12:20

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_memberprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE'),
        ),
    ]
