# Generated by Django 5.2.1 on 2025-05-28 08:08

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_memberprofile_phone_number'),
        ('base', '0007_statement_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='base.committee'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='KE'),
        ),
    ]
