# Generated by Django 5.2.1 on 2025-05-28 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_memberprofile_committee_and_more'),
        ('base', '0008_directorate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='committee',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='directorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='base.directorate'),
        ),
    ]
