# Generated by Django 5.2.1 on 2025-05-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_memberprofile_committee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='first_name',
            field=models.CharField(default='James', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='last_name',
            field=models.CharField(default='Maina', max_length=200),
            preserve_default=False,
        ),
    ]
