# Generated by Django 5.2.1 on 2025-05-21 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='committee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.committee'),
            preserve_default=False,
        ),
    ]
