# Generated by Django 5.2.1 on 2025-05-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_statement_committee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='file',
            field=models.FileField(upload_to='statements/'),
        ),
    ]
