# Generated by Django 5.2.1 on 2025-05-22 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_statement_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='base.committee'),
        ),
    ]
