# Generated by Django 5.2.1 on 2025-05-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_statement_committee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='name',
        ),
    ]
