# Generated by Django 5.2.1 on 2025-05-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_statement_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
