# Generated by Django 5.2.1 on 2025-05-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_directorate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorate',
            name='mandate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
