# Generated by Django 5.2.1 on 2025-06-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_directorate_mandate'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='chair',
            field=models.TextField(default='Chesang', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='committee',
            name='shorthand',
            field=models.TextField(default='ICT', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='committee',
            name='vice',
            field=models.TextField(default='Miraj', max_length=200),
            preserve_default=False,
        ),
    ]
