# Generated by Django 5.2.1 on 2025-06-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_committee_chair_committee_shorthand_committee_vice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='chair',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='committee',
            name='shorthand',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='committee',
            name='vice',
            field=models.CharField(max_length=200),
        ),
    ]
